steps:
  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Compute Engine Instance'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'gcp-exercise1'          
      - '--zone=us-central1-a'         
      - '--machine-type=n1-standard-2'  
      - '--image-family=windows-2019'   
      - '--image-project=windows-cloud' 
      - '--boot-disk-size=50GB'         
      - '--boot-disk-type=pd-standard'  
      - '--metadata=windows-startup-script-ps1=Add-LocalUser -Name "admin_user" -Password (ConvertTo-SecureString "AdminPassword123!" -AsPlainText -Force); Add-LocalGroupMember -Group "Administrators" -Member "admin_user"'
      - '--tags=http-server,https-server'  


serviceAccount: '11391129857-compute@developer.gserviceaccount.com'  
logsBucket: 'gs://test-gcsex'           
timeout: '1200s'


substitutions:
  _INSTANCE_NAME: 'gcp-exercise1'

